export const ignoredKeys = [
  'Site_Code',
  'Data_Type',
  'SiteName',
  'Site_Name',
  'Wid',
  'ID'
];
export const keyLookup = {
  'SiteName': {title: 'Site Name', desc: ''},
  'Site_Name': {title: 'Site Name', desc: ''},
  'Wid': {title: 'WID', desc: ''},
  'ID': {title: 'ID', desc: ''},
  'RecentLog': {title: 'Most recent log', desc: ''},
  'MaxDepth': {title: 'Max depth (ft)', desc: ''},
  'Norm_Res': {title: 'Normal Resistivity', desc: ''},
  'Caliper': {title: 'Caliper', desc: ''},
  'Gamma': {title: 'Natural Gamma', desc: ''},
  'SP': {title: 'Spontaneous (Self) Potential', desc: ''},
  'SPR': {title: 'Single Point Resistivity', desc: ''},
  'Spec_Gamma': {title: 'Spectral Gamma', desc: ''},
  'Fluid_Cond': {title: 'Fluid Conductivity', desc: ''},
  'Flow_Spin': {title: 'Spinner Flow Meter', desc: ''},
  'Fluid_Temp': {title: 'Fluid Temperature', desc: ''},
  'Fluid_Res': {title: 'Fluid Resistivity', desc: ''},
  'OBI': {title: 'Optical Borehole Image (OBI)', desc: ''},
  'ABI': {title: 'Acoustic Borehole Image (ABI)', desc: ''},
  'Video': {title: 'Video', desc: ''},
  'Drill_Year': {title: 'Drill year', desc: ''},
  'Depth_Ft': {title: 'Depth (ft)', desc: ''},
  'Drill_Meth': {title: 'Drill Method', desc: ''},
  'Subsamples': {title: 'Subsamples', desc: ''},
  'Photos': {title: 'Core Photos', desc: ''},
  'Grainsize': {title: 'Grainsize', desc: ''},
};